cache:
  paths:
  - node_modules/

stages:
  - build
  
deploy:
  stage: build
  script:
    - echo "build"

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - master